export const tokens = {
  colors: {
    bgCanvas: 'var(--color-canvas)',
    bgSurface: 'var(--color-surface-container-lowest)',
    bgSubtle: 'var(--color-surface-container-low)',
    bgMuted: 'var(--color-bg-muted)',
    bgDisabled: 'var(--color-bg-disabled)',
    border: 'var(--color-border-muted)',
    borderDefault: 'var(--color-border-default)',
    borderField: 'var(--color-border-field)',
    borderStrong: 'var(--color-border-strong)',
    textSecondary: 'var(--color-text-secondary-exact)',
    textPrimary: 'var(--color-text-primary)',
    textTertiary: 'var(--color-text-tertiary)',
    textDisabled: 'var(--color-text-disabled)',

    brand50: 'var(--color-brand-50)',
    brand100: 'var(--color-brand-100)',
    brand200: 'var(--color-brand-200)',
    brand300: 'var(--color-brand-300)',
    brand400: 'var(--color-brand-400)',
    brand500: 'var(--color-brand-500)',
    brand600: 'var(--color-brand-600)',
    brand700: 'var(--color-brand-700)',

    success50: 'var(--color-success-50-exact)',
    success500: 'var(--color-success-500-exact)',
    success700: 'var(--color-success-700-exact)',
    warning50: 'var(--color-warning-50-exact)',
    warning500: 'var(--color-warning-500-exact)',
    warning700: 'var(--color-warning-700-exact)',
    danger50: 'var(--color-danger-50-exact)',
    danger500: 'var(--color-danger-500-exact)',
    dangerHover: 'var(--color-danger-600-exact)',
    dangerPressed: 'var(--color-danger-700-exact)',
    info50: 'var(--color-info-50-exact)',
    info500: 'var(--color-info-500-exact)',
    info700: 'var(--color-info-700-exact)',

    kgConcept: 'var(--color-kg-concept)',
    kgMethod: 'var(--color-success-500-exact)',
    kgDataset: 'var(--color-warning-500-exact)',
    kgMetric: 'var(--color-info-500-exact)',
    kgAuthor: 'var(--color-kg-author)',
    kgVenue: 'var(--color-kg-venue)',
  },
  radius: {
    control: 'var(--radius-control)',
    field: 'var(--radius-field)',
    card: 'var(--radius-card)',
    popover: 'var(--radius-popover)',
    dialog: 'var(--radius-dialog)',
    modal: 'var(--radius-modal)',
    drawer: 'var(--radius-drawer)',
    xs: 'var(--radius-xs)',
    sm: 'var(--radius-sm)',
    pill: 'var(--radius-pill)',
  },
  shadow: {
    none: 'var(--shadow-none)',
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    modal: 'var(--shadow-modal)',
    drawer: 'var(--shadow-side-drawer)',
    dropdown: 'var(--shadow-dropdown)',
    focus: 'var(--shadow-focus)',
    focusDanger: 'var(--shadow-focus-danger)',
  },
  motion: {
    fast: 'var(--motion-duration-fast)',
    normal: 'var(--motion-duration-normal)',
    medium: 'var(--motion-duration-medium)',
    modal: 'var(--motion-duration-modal)',
    spring: 'var(--motion-duration-spring)',
    ease: 'var(--motion-ease-standard)',
    springEase: 'var(--motion-ease-spring)',
  },
  zIndex: {
    dropdown: 'var(--z-dropdown)',
    shell: 'var(--z-shell)',
    drawer: 'var(--z-drawer)',
    modal: 'var(--z-modal)',
    cmdk: 'var(--z-cmdk)',
    popover: 'var(--z-popover)',
    toast: 'var(--z-toast)',
  },
}
